### ISSUE TITLE
Attaching files to protocols

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#134]
When we want to add a file to protocol, we first need to create a document that has an attachment and then add this document to protocol. This seems too nested. Can we directly have attachment in the protocol. The two will be separate collections anyway.

**Comment by aschroed** [comment]
If you think it makes sense we can add the attachments mixin to Protocol (and specific sub protocols). The advantage of the nested structure is allowing a description, possible links to external sites and a controlled document type that are linked to the attachment.  But I think you are saying that the link is not explicit since they are in separate collections.  However, we would probably include an 'attached file' column in the Document collection view.  But since the 'bare' attachment is linked to the protocol it is kind of explicitly a protocol document so that is sufficient.  

I think if we can add a 'description' property to the attachment mixin that will get us most of the way there and will also potentially make the 'attachment' collection more informative.

**Comment by KorayKirli** [comment]
I will keep it the way it was, we can change it later if we need to.
