### ISSUE TITLE
Multiple Restriction enzymes in an experiment

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#137]
2 experiments in Rao et al are done with 3 restriction enzymes, this seems to be a very specific case, we can 
1)ignore this and add it in the description
2)add 3 enzyme mix in the enzymes
3)change schema to take multiple enzymes

I am not sure how often we see this, so thinking option 2 might be a temporary solution.

**Comment by aschroed** [comment]
I think your option 2 might be the correct solution.  Thinking about it from the perspective of someone searching for experiments using a specific enzyme it may be more confusing if a search returned results that included experiments such as this that included the specific enzyme they were searching with as well as others with an 'equal' ranking as those that just used the single enzyme they were looking for.  Making a 3 enzyme mix enzyme item would likely allow the result to be returned by search for any of the included enzymes but because the match for the search would be less good the result would end up lower in the list.  The problem would be if this occurred frequently then we would need many combinations of enzyme as enzyme items but I suspect it might not be that common.  We could ask the Lieberman lab for their opinion as an initial ice breaker question?

**Comment by KorayKirli** [comment]
Going with option 2
